# Generated by Django 3.2.7 on 2021-11-23 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Herb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rarity', models.CharField(choices=[('U', 'Uncommon'), ('C', 'Common')], default='U', max_length=1)),
                ('info', models.TextField(max_length=250)),
                ('uses', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Remedy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('T', 'Tonic'), ('P', 'Poultice'), ('S', 'Sachet')], default='T', max_length=1)),
                ('description', models.TextField(max_length=500)),
                ('herbs', models.ManyToManyField(to='main_app.Herb')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
