# Generated by Django 3.2.7 on 2021-11-30 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20211129_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remedy',
            name='herbs',
            field=models.ManyToManyField(help_text='Hold down “Control”, or “Command” on a Mac, to select more than one.', to='main_app.Herb'),
        ),
    ]
